application:
  host: 127.0.0.1
  port: 8000
  base_url: "http://127.0.0.1"
database:
  host: 127.0.0.1
  port: 5432
  username: "vincent"
  password: "vincent"
  database_name: zero2prod
tem:
  base_url: "https://api.scaleway.com/transactional-email/v1alpha1/regions/fr-par"
  project_id: "myprojectid"
  auth_key: "myauthkey"
  sender_email: "vincent@zero2prod.rischmann.fr"
  timeout_milliseconds: 10000
